In [1]:
import pandas as pd

In [2]:
df= pd.read_excel("Amazon.xlsx")

In [4]:
df

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,0.00,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,0.05,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298
2,ORD0000003,2022-05-10,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,0.10,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908
3,ORD0000004,2023-07-18,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,0.15,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164
4,ORD0000005,2023-02-04,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,0.25,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,ORD0099996,2023-03-07,CUST001356,Karan Joshi,P00047,Memory Card 128GB,Electronics,Apex,2,492.34,0.00,78.77,2.75,1066.20,UPI,Delivered,Jacksonville,FL,India,SELL00041
99996,ORD0099997,2021-11-24,CUST031254,Sunita Kapoor,P00046,Car Charger,Sports & Outdoors,Apex,5,449.30,0.00,179.72,6.07,2432.29,Credit Card,Delivered,San Jose,CA,United States,SELL01449
99997,ORD0099998,2023-04-29,CUST012579,Aman Gupta,P00030,Dress Shirt,Sports & Outdoors,BrightLux,4,232.40,0.00,74.37,12.43,1016.40,Cash on Delivery,Delivered,Indianapolis,IN,United States,SELL00028
99998,ORD0099999,2021-11-01,CUST026243,Simran Gupta,P00046,Car Charger,Sports & Outdoors,HomeEase,1,294.05,0.00,23.52,13.09,330.66,Debit Card,Delivered,Charlotte,NC,United States,SELL00324
99999,ORD0100000,2021-12-04,CUST029492,Sunita Reddy,P00019,LED Desk Lamp,Home & Kitchen,CoreTech,5,166.70,0.05,63.35,3.34,858.52,Debit Card,Delivered,New York,NY,United States,SELL00761

In [5]:
df.shape

(100000, 20)

In [6]:
df.isnull().sum()

OrderID          0
OrderDate        0
CustomerID       0
CustomerName     0
ProductID        0
ProductName      0
Category         0
Brand            0
Quantity         0
UnitPrice        0
Discount         0
Tax              0
ShippingCost     0
TotalAmount      0
PaymentMethod    0
OrderStatus      0
City             0
State            0
Country          0
SellerID         0
dtype: int64

In [14]:
df.columns

Index(['OrderID', 'OrderDate', 'CustomerID', 'CustomerName', 'ProductID',
       'ProductName', 'Category', 'Brand', 'Quantity', 'UnitPrice', 'Discount',
       'Tax', 'ShippingCost', 'TotalAmount', 'PaymentMethod', 'OrderStatus',
       'City', 'State', 'Country', 'SellerID'],
      dtype='str')

In [17]:
for col in df.columns:
    print(col,df[col].unique)

OrderID <bound method Series.unique of 0        ORD0000001
1        ORD0000002
2        ORD0000003
3        ORD0000004
4        ORD0000005
            ...
99995    ORD0099996
99996    ORD0099997
99997    ORD0099998
99998    ORD0099999
99999    ORD0100000
Name: OrderID, Length: 100000, dtype: str>
OrderDate <bound method Series.unique of 0       2023-01-31
1       2023-12-30
2       2022-05-10
3       2023-07-18
4       2023-02-04
           ...
99995   2023-03-07
99996   2021-11-24
99997   2023-04-29
99998   2021-11-01
99999   2021-12-04
Name: OrderDate, Length: 100000, dtype: datetime64[us]>
CustomerID <bound method Series.unique of 0        CUST001504
1        CUST000178
2        CUST047516
3        CUST030059
4        CUST048677
            ...
99995    CUST001356
99996    CUST031254
99997    CUST012579
99998    CUST026243
99999    CUST029492
Name: CustomerID, Length: 100000, dtype: str>
CustomerName <bound method Series.unique of 0        Vihaan Sharma
1          Pooja Kumar
2          Sneha Singh
3         Vihaan Reddy
4        Aditya Kapoor
             ...
99995      Karan Joshi
99996    Sunita Kapoor
99997       Aman Gupta
99998     Simran Gupta
99999     Sunita Reddy
Name: CustomerName, Length: 100000, dtype: str>
ProductID <bound method Series.unique of 0        P00014
1        P00040
2        P00044
3        P00041
4        P00029
          ...
99995    P00047
99996    P00046
99997    P00030
99998    P00046
99999    P00019
Name: ProductID, Length: 100000, dtype: str>
ProductName <bound method Series.unique of 0                 Drone Mini
1                 Microphone
2        Power Bank 20000mAh
3             Webcam Full HD
4                    T-Shirt
                ...
99995      Memory Card 128GB
99996            Car Charger
99997            Dress Shirt
99998            Car Charger
99999          LED Desk Lamp
Name: ProductName, Length: 100000, dtype: str>
Category <bound method Series.unique of 0                    Books
1           Home & Kitchen
2                 Clothing
3           Home & Kitchen
4                 Clothing
               ...
99995          Electronics
99996    Sports & Outdoors
99997    Sports & Outdoors
99998    Sports & Outdoors
99999       Home & Kitchen
Name: Category, Length: 100000, dtype: str>
Brand <bound method Series.unique of 0         BrightLux
1        UrbanStyle
2        UrbanStyle
3            Zenith
4          KiddoFun
            ...
99995          Apex
99996          Apex
99997     BrightLux
99998      HomeEase
99999      CoreTech
Name: Brand, Length: 100000, dtype: str>
Quantity <bound method Series.unique of 0        3
1        1
2        3
3        5
4        2
        ..
99995    2
99996    5
99997    4
99998    1
99999    5
Name: Quantity, Length: 100000, dtype: int64>
UnitPrice <bound method Series.unique of 0        106.59
1        251.37
2         35.03
3         33.58
4        515.64
          ...
99995    492.34
99996    449.30
99997    232.40
99998    294.05
99999    166.70
Name: UnitPrice, Length: 100000, dtype: float64>
Discount <bound method Series.unique of 0        0.00
1        0.05
2        0.10
3        0.15
4        0.25
         ...
99995    0.00
99996    0.00
99997    0.00
99998    0.00
99999    0.05
Name: Discount, Length: 100000, dtype: float64>
Tax <bound method Series.unique of 0          0.00
1         19.10
2          7.57
3         11.42
4         38.67
          ...
99995     78.77
99996    179.72
99997     74.37
99998     23.52
99999     63.35
Name: Tax, Length: 100000, dtype: float64>
ShippingCost <bound method Series.unique of 0         0.09
1         1.74
2         5.91
3         5.53
4         9.23
         ...
99995     2.75
99996     6.07
99997    12.43
99998    13.09
99999     3.34
Name: ShippingCost, Length: 100000, dtype: float64>
TotalAmount <bound method Series.unique of 0         319.86
1         259.64
2         108.06
3         159.66
4         821.36
          ...
99995    1066.20
99996    2432.29
99997    1016.40
99998     330.66
99999     858.52
Name: TotalAmount, Length: 100000, dtype: float64>
PaymentMethod <bound method Series.unique of 0              Debit Card
1              Amazon Pay
2              Debit Card
3        Cash on Delivery
4             Credit Card
               ...
99995                 UPI
99996         Credit Card
99997    Cash on Delivery
99998          Debit Card
99999          Debit Card
Name: PaymentMethod, Length: 100000, dtype: str>
OrderStatus <bound method Series.unique of 0        Delivered
1        Delivered
2        Delivered
3        Delivered
4        Cancelled
           ...
99995    Delivered
99996    Delivered
99997    Delivered
99998    Delivered
99999    Delivered
Name: OrderStatus, Length: 100000, dtype: str>
City <bound method Series.unique of 0          Washington
1          Fort Worth
2              Austin
3           Charlotte
4         San Antonio
             ...
99995    Jacksonville
99996        San Jose
99997    Indianapolis
99998       Charlotte
99999        New York
Name: City, Length: 100000, dtype: str>
State <bound method Series.unique of 0        DC
1        TX
2        TX
3        NC
4        TX
         ..
99995    FL
99996    CA
99997    IN
99998    NC
99999    NY
Name: State, Length: 100000, dtype: str>
Country <bound method Series.unique of 0                India
1        United States
2        United States
3                India
4               Canada
             ...
99995            India
99996    United States
99997    United States
99998    United States
99999    United States
Name: Country, Length: 100000, dtype: str>
SellerID <bound method Series.unique of 0        SELL01967
1        SELL01298
2        SELL00908
3        SELL01164
4        SELL01411
           ...
99995    SELL00041
99996    SELL01449
99997    SELL00028
99998    SELL00324
99999    SELL00761
Name: SellerID, Length: 100000, dtype: str>

In [18]:
df.drop_duplicates(inplace=True)

In [19]:
df.shape

(100000, 20)

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   OrderID        100000 non-null  str
 1   OrderDate      100000 non-null  datetime64[us]
 2   CustomerID     100000 non-null  str
 3   CustomerName   100000 non-null  str
 4   ProductID      100000 non-null  str
 5   ProductName    100000 non-null  str
 6   Category       100000 non-null  str
 7   Brand          100000 non-null  str
 8   Quantity       100000 non-null  int64
 9   UnitPrice      100000 non-null  float64
 10  Discount       100000 non-null  float64
 11  Tax            100000 non-null  float64
 12  ShippingCost   100000 non-null  float64
 13  TotalAmount    100000 non-null  float64
 14  PaymentMethod  100000 non-null  str
 15  OrderStatus    100000 non-null  str
 16  City           100000 non-null  str
 17  State          100000 non-null  str
 18  Country        100000 non-null  str
 19  SellerID       100000 non-null  str
dtypes: datetime64[us](1), float64(5), int64(1), str(13)
memory usage: 15.3 MB

In [23]:
df['Total Sales']=df['UnitPrice']*df['Quantity']

In [25]:
df['UnitPrice'].unique()

array([106.59, 251.37,  35.03, ...,  87.95, 354.58, 204.73],
      shape=(48433,))

In [24]:
df.head()

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,...,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID,Total Sales
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,...,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967,319.77
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,...,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298,251.37
2,ORD0000003,2022-05-10,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,...,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908,105.09
3,ORD0000004,2023-07-18,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,...,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164,167.90
4,ORD0000005,2023-02-04,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,...,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411,1031.28

In [28]:
df.to_excel("Amazon.xlsx")

In [30]:
df.to_excel(r"C:\Users\JEEVA NANDHAM\OneDrive\Documents\Amazon.xlsx", index=False)